server:
  port: 8080
spring:
  datasource:
    username: root
    password: testTest
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://1c.ru
      name: 1C
    - url: https://ezo-restoran.ru
      name: ЭЗО
    - url: https://zdraste-schastie.ru
      name: Здрасте счастье
#    - url: https://skillbox.ru
#      name: Skillbox
#    - url: https://lenta.ru
#      name: Лента.ру
#    - url: https://www.playback.ru
#      name: PlayBack.Ru