server:
  port: 8080
spring:
  datasource:
    username: root
    password: testTest
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:

  userAgent: DeepSearchBot
  referrer: http://www.google.com
  redirect: true
  sleep: 200
  timeout: 10000

  sites:
#    - url: https://ipfran.ru/
#      name: IP Fran
    - url: https://www.lutherancathedral.ru/
      name: Lutheran Cathedral
    - url: https://www.svetlovka.ru/
      name: Svetlovka
    - url: https://www.programmaster.ru
      name: Program Master
#    - url: https://dombulgakova.ru/
#      name: Дом Булгакова
    - url: https://ezo-restoran.ru
      name: ЭЗО
    - url: https://zdraste-schastie.ru
      name: Здрасте счастье
    - url: https://1c.ru/
      name: 1C
    - url: https://et-cetera.ru/mobile/
      name: ET Cetera
#    - url: https://skillbox.ru
#      name: Skillbox
#    - url: https://lenta.ru
#      name: Лента.ру
#    - url: https://www.playback.ru
#      name: PlayBack