server:
  port: 8080

spring:
  datasource:
    username: root
    password: testTest
    # prod db: search_engine / test db: search_engine_test
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1500
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    jcache:
      type: ehcache
      ehcache:
        config: src/main/resources/ehcache.xml

search-settings:
  maxFrequencyInPercent: 15
  snippetLength: 230

error-settings:
  startIndexingError: Индексация уже запущена
  stopIndexingError: Индексация не запущена
  indexingInterruptedError: Индексация остановлена пользователем
  siteOutOfConfigError: Данная страница находится за пределами сайтов, указанных в конфигурационном файле
  siteIsIndexingError: Данный сайт находится в процессе индексации
  mainPageUnavailableError: Главная страница недоступна
  emptyQuerySearchError: Задан пустой поисковый запрос
  badRequestError: Неправильный запрос
  unauthorizedError: Ошибка авторизации
  forbiddenError: Доступ к запрошенному ресурсу запрещен
  methodNotAllowedError: Метод недоступен
  notFoundError: Указанная страница не найдена
  internalServerError: Внутрення ошибка сервера

indexing-settings:
  userAgent: DeepSearchBot
  referrer: http://www.google.com
  redirect: true
  sleep: 200
  timeout: 10000
  ignoreHttpErrors: true
  sites:
    - url: https://ipfran.ru/ # prod version
      name: IP Fran
    - url: https://www.lutherancathedral.ru/ # prod version
      name: Lutheran Cathedral
    - url: https://www.svetlovka.ru/ # prod version
      name: Svetlovka
    - url: https://www.programmaster.ru # prod version
      name: Program Master
    - url: https://et-cetera.ru/mobile/ # prod version
      name: ET Cetera
    - url: https://skillbox.ru # prod version
      name: Skillbox
#    - url: https://lenta.ru
#      name: Лента.ру
    - url: https://www.playback.ru # prod version
      name: PlayBack